services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: countries_sql_server
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=A&VeryComplex123Password
      - MSSQL_PID=Express
  web_api:
    image: countries_api_image:latest
    container_name: countries_api
    depends_on: 
        - sql
    ports:
      - "5000:8080"
  